# Generated by Django 2.1 on 2019-11-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191107_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_have_piece_of_pizza', 'Может съесть кусочек пиццы')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
