# Generated by Django 2.1 on 2019-11-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191114_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_order',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
